/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : c_src/Mud.g
 *     -                            On : 2012-09-23 18:38:48
 *     -                for the parser : MudParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <erl_nif.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MudParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMudParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMudParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMudParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMudParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   MudParserTokenNames[8+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "DIRECTION",
        (pANTLR3_UINT8) "TEXT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'around'",
        (pANTLR3_UINT8) "'at'",
        (pANTLR3_UINT8) "'login'",
        (pANTLR3_UINT8) "'look'",
        (pANTLR3_UINT8) "'move'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ERL_NIF_TERM
	command    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	login    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	look    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	move    (pMudParser ctx, ErlNifEnv *env);
static void	MudParserFree(pMudParser ctx);
static void     MudParserReset (pMudParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "c_src/Mud.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new MudParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMudParser
MudParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return MudParserNewSSD(instream, NULL);
}

/** \brief Create a new MudParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMudParser
MudParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMudParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pMudParser) ANTLR3_CALLOC(1, sizeof(MudParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MudParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our MudParser interface
     */
    ctx->command	= command;
    ctx->login	= login;
    ctx->look	= look;
    ctx->move	= move;
    ctx->free			= MudParserFree;
    ctx->reset			= MudParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = MudParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
MudParserReset (pMudParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 MudParserFree(pMudParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return MudParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_login_in_command41  */
static	ANTLR3_BITWORD FOLLOW_login_in_command41_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_login_in_command41	= { FOLLOW_login_in_command41_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_look_in_command53  */
static	ANTLR3_BITWORD FOLLOW_look_in_command53_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_look_in_command53	= { FOLLOW_look_in_command53_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_move_in_command64  */
static	ANTLR3_BITWORD FOLLOW_move_in_command64_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_move_in_command64	= { FOLLOW_move_in_command64_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_login89  */
static	ANTLR3_BITWORD FOLLOW_9_in_login89_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_login89	= { FOLLOW_9_in_login89_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_login91  */
static	ANTLR3_BITWORD FOLLOW_WS_in_login91_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_login91	= { FOLLOW_WS_in_login91_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_login93  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_login93_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_login93	= { FOLLOW_TEXT_in_login93_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_login95  */
static	ANTLR3_BITWORD FOLLOW_WS_in_login95_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_login95	= { FOLLOW_WS_in_login95_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_login97  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_login97_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_login97	= { FOLLOW_TEXT_in_login97_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_look121  */
static	ANTLR3_BITWORD FOLLOW_10_in_look121_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_look121	= { FOLLOW_10_in_look121_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_look131  */
static	ANTLR3_BITWORD FOLLOW_10_in_look131_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_look131	= { FOLLOW_10_in_look131_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_look133  */
static	ANTLR3_BITWORD FOLLOW_WS_in_look133_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_look133	= { FOLLOW_WS_in_look133_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_7_in_look135  */
static	ANTLR3_BITWORD FOLLOW_7_in_look135_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_7_in_look135	= { FOLLOW_7_in_look135_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_look144  */
static	ANTLR3_BITWORD FOLLOW_10_in_look144_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_look144	= { FOLLOW_10_in_look144_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_look146  */
static	ANTLR3_BITWORD FOLLOW_WS_in_look146_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_look146	= { FOLLOW_WS_in_look146_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_look148  */
static	ANTLR3_BITWORD FOLLOW_8_in_look148_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_look148	= { FOLLOW_8_in_look148_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_look150  */
static	ANTLR3_BITWORD FOLLOW_WS_in_look150_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_look150	= { FOLLOW_WS_in_look150_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_look154  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_look154_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_look154	= { FOLLOW_TEXT_in_look154_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_move177  */
static	ANTLR3_BITWORD FOLLOW_11_in_move177_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_move177	= { FOLLOW_11_in_move177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_move179  */
static	ANTLR3_BITWORD FOLLOW_WS_in_move179_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_move179	= { FOLLOW_WS_in_move179_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DIRECTION_in_move181  */
static	ANTLR3_BITWORD FOLLOW_DIRECTION_in_move181_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_DIRECTION_in_move181	= { FOLLOW_DIRECTION_in_move181_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DIRECTION_in_move190  */
static	ANTLR3_BITWORD FOLLOW_DIRECTION_in_move190_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_DIRECTION_in_move190	= { FOLLOW_DIRECTION_in_move190_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start command
 * c_src/Mud.g:11:1: command[ErlNifEnv *env] returns [ERL_NIF_TERM value] : ( login[env] | look[env] | move[env] );
 */
static ERL_NIF_TERM
command(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    ERL_NIF_TERM login1;
    #undef	RETURN_TYPE_login1
    #define	RETURN_TYPE_login1 ERL_NIF_TERM

    ERL_NIF_TERM look2;
    #undef	RETURN_TYPE_look2
    #define	RETURN_TYPE_look2 ERL_NIF_TERM

    ERL_NIF_TERM move3;
    #undef	RETURN_TYPE_move3
    #define	RETURN_TYPE_move3 ERL_NIF_TERM

    /* Initialize rule variables
     */

    {
        {
            //  c_src/Mud.g:12:5: ( login[env] | look[env] | move[env] )

            ANTLR3_UINT32 alt1;

            alt1=3;

            switch ( LA(1) )
            {
            case 9:
            	{
            		alt1=1;
            	}
                break;
            case 10:
            	{
            		alt1=2;
            	}
                break;
            case DIRECTION:
            case 11:
            	{
            		alt1=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 1;
                EXCEPTION->state        = 0;


                goto rulecommandEx;

            }

            switch (alt1)
            {
        	case 1:
        	    // c_src/Mud.g:12:7: login[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_login_in_command41);
        	        login1=login(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            login1
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 2:
        	    // c_src/Mud.g:13:7: look[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_look_in_command53);
        	        look2=look(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            look2
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 3:
        	    // c_src/Mud.g:14:7: move[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_move_in_command64);
        	        move3=move(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            move3
        	            ;
        	             
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulecommandEx; /* Prevent compiler warnings */
    rulecommandEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return value;
}
/* $ANTLR end command */

/**
 * $ANTLR start login
 * c_src/Mud.g:17:1: login[ErlNifEnv *env] returns [ERL_NIF_TERM value] : 'login' WS TEXT WS TEXT ;
 */
static ERL_NIF_TERM
login(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    /* Initialize rule variables
     */

    {
        // c_src/Mud.g:18:5: ( 'login' WS TEXT WS TEXT )
        // c_src/Mud.g:18:7: 'login' WS TEXT WS TEXT
        {
             MATCHT(9, &FOLLOW_9_in_login89);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_login91);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


             MATCHT(TEXT, &FOLLOW_TEXT_in_login93);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_login95);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


             MATCHT(TEXT, &FOLLOW_TEXT_in_login97);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


            {

                            ERL_NIF_TERM tag = enif_make_atom(env, "cmd");
                            ERL_NIF_TERM cmd = enif_make_atom(env, "login");
                            ERL_NIF_TERM sessid = enif_make_atom(env, "undefined");
                            ERL_NIF_TERM props = enif_make_list(env, 0);

                            value= enif_make_tuple(env, 4, tag, cmd, sessid, props);

                        
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleloginEx; /* Prevent compiler warnings */
    ruleloginEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return value;
}
/* $ANTLR end login */

/**
 * $ANTLR start look
 * c_src/Mud.g:28:1: look[ErlNifEnv *env] returns [ERL_NIF_TERM value] : ( 'look' | 'look' WS 'around' | 'look' WS 'at' WS target= TEXT );
 */
static ERL_NIF_TERM
look(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    pANTLR3_COMMON_TOKEN    target;

    /* Initialize rule variables
     */

    target       = NULL;

    {
        {
            //  c_src/Mud.g:29:5: ( 'look' | 'look' WS 'around' | 'look' WS 'at' WS target= TEXT )

            ANTLR3_UINT32 alt2;

            alt2=3;

            switch ( LA(1) )
            {
            case 10:
            	{
            		switch ( LA(2) )
            		{
            		case WS:
            			{
            				switch ( LA(3) )
            				{
            				case 7:
            					{
            						alt2=2;
            					}
            				    break;
            				case 8:
            					{
            						alt2=3;
            					}
            				    break;

            				default:
            				    CONSTRUCTEX();
            				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            				    EXCEPTION->message      = (void *)"";
            				    EXCEPTION->decisionNum  = 2;
            				    EXCEPTION->state        = 2;


            				    goto rulelookEx;

            				}

            			}
            		    break;
            		case EOF:
            			{
            				alt2=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 2;
            		    EXCEPTION->state        = 1;


            		    goto rulelookEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulelookEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // c_src/Mud.g:29:7: 'look'
        	    {
        	         MATCHT(10, &FOLLOW_10_in_look121);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // c_src/Mud.g:30:7: 'look' WS 'around'
        	    {
        	         MATCHT(10, &FOLLOW_10_in_look131);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	         MATCHT(WS, &FOLLOW_WS_in_look133);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	         MATCHT(7, &FOLLOW_7_in_look135);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // c_src/Mud.g:31:7: 'look' WS 'at' WS target= TEXT
        	    {
        	         MATCHT(10, &FOLLOW_10_in_look144);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	         MATCHT(WS, &FOLLOW_WS_in_look146);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	         MATCHT(8, &FOLLOW_8_in_look148);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	         MATCHT(WS, &FOLLOW_WS_in_look150);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	        target = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_look154);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulelookEx; /* Prevent compiler warnings */
    rulelookEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return value;
}
/* $ANTLR end look */

/**
 * $ANTLR start move
 * c_src/Mud.g:34:1: move[ErlNifEnv *env] returns [ERL_NIF_TERM value] : ( 'move' WS DIRECTION | DIRECTION );
 */
static ERL_NIF_TERM
move(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    /* Initialize rule variables
     */

    {
        {
            //  c_src/Mud.g:35:5: ( 'move' WS DIRECTION | DIRECTION )

            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) )
            {
            case 11:
            	{
            		alt3=1;
            	}
                break;
            case DIRECTION:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto rulemoveEx;

            }

            switch (alt3)
            {
        	case 1:
        	    // c_src/Mud.g:35:7: 'move' WS DIRECTION
        	    {
        	         MATCHT(11, &FOLLOW_11_in_move177);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulemoveEx;
        	        }


        	         MATCHT(WS, &FOLLOW_WS_in_move179);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulemoveEx;
        	        }


        	         MATCHT(DIRECTION, &FOLLOW_DIRECTION_in_move181);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulemoveEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // c_src/Mud.g:36:7: DIRECTION
        	    {
        	         MATCHT(DIRECTION, &FOLLOW_DIRECTION_in_move190);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulemoveEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulemoveEx; /* Prevent compiler warnings */
    rulemoveEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return value;
}
/* $ANTLR end move */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
