/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : c_src/Mud.g
 *     -                            On : 2012-09-26 23:13:10
 *     -                for the parser : MudParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "MudParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pMudParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pMudParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pMudParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pMudParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   MudParserTokenNames[11+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "TEXT",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'around'",
        (pANTLR3_UINT8) "'at'",
        (pANTLR3_UINT8) "'create user'",
        (pANTLR3_UINT8) "'join as'",
        (pANTLR3_UINT8) "'login'",
        (pANTLR3_UINT8) "'look'",
        (pANTLR3_UINT8) "'move'",
        (pANTLR3_UINT8) "'my name is'",
        (pANTLR3_UINT8) "'new character'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ERL_NIF_TERM
	command    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	new_user    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	new_character    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	character_name    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	pick_character    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	login    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	look    (pMudParser ctx, ErlNifEnv *env);
static 
 ERL_NIF_TERM
	move    (pMudParser ctx, ErlNifEnv *env);
static void	MudParserFree(pMudParser ctx);
static void     MudParserReset (pMudParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "c_src/Mud.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new MudParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMudParser
MudParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return MudParserNewSSD(instream, NULL);
}

/** \brief Create a new MudParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pMudParser
MudParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pMudParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pMudParser) ANTLR3_CALLOC(1, sizeof(MudParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in MudParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our MudParser interface
     */
    ctx->command	= command;
    ctx->new_user	= new_user;
    ctx->new_character	= new_character;
    ctx->character_name	= character_name;
    ctx->pick_character	= pick_character;
    ctx->login	= login;
    ctx->look	= look;
    ctx->move	= move;
    ctx->free			= MudParserFree;
    ctx->reset			= MudParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = MudParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
MudParserReset (pMudParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 MudParserFree(pMudParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return MudParserTokenNames;
}


        ERL_NIF_TERM make_binary(ErlNifEnv *env, pANTLR3_COMMON_TOKEN token) {
            ErlNifBinary bin;
            pANTLR3_STRING text = token->getText(token);
            pANTLR3_STRING unicode = text->toUTF8(text);

            enif_alloc_binary(unicode->len, &bin);
            memcpy(bin.data, unicode->chars, unicode->len); 
            return enif_make_binary(env, &bin);
        }

        ERL_NIF_TERM make_cmd(ErlNifEnv *env, char *cmd, ERL_NIF_TERM props){
            return enif_make_tuple(env, 4, A("cmd"), A(cmd), 
                                   A("undefined"), props);
        }


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_new_user_in_command51  */
static	ANTLR3_BITWORD FOLLOW_new_user_in_command51_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_new_user_in_command51	= { FOLLOW_new_user_in_command51_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_new_character_in_command65  */
static	ANTLR3_BITWORD FOLLOW_new_character_in_command65_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_new_character_in_command65	= { FOLLOW_new_character_in_command65_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_character_name_in_command79  */
static	ANTLR3_BITWORD FOLLOW_character_name_in_command79_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_character_name_in_command79	= { FOLLOW_character_name_in_command79_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_pick_character_in_command92  */
static	ANTLR3_BITWORD FOLLOW_pick_character_in_command92_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_pick_character_in_command92	= { FOLLOW_pick_character_in_command92_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_login_in_command106  */
static	ANTLR3_BITWORD FOLLOW_login_in_command106_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_login_in_command106	= { FOLLOW_login_in_command106_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_look_in_command120  */
static	ANTLR3_BITWORD FOLLOW_look_in_command120_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_look_in_command120	= { FOLLOW_look_in_command120_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_move_in_command133  */
static	ANTLR3_BITWORD FOLLOW_move_in_command133_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_move_in_command133	= { FOLLOW_move_in_command133_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_new_user167  */
static	ANTLR3_BITWORD FOLLOW_8_in_new_user167_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_new_user167	= { FOLLOW_8_in_new_user167_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_new_user169  */
static	ANTLR3_BITWORD FOLLOW_WS_in_new_user169_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_new_user169	= { FOLLOW_WS_in_new_user169_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_new_user173  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_new_user173_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_new_user173	= { FOLLOW_TEXT_in_new_user173_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_new_user175  */
static	ANTLR3_BITWORD FOLLOW_WS_in_new_user175_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_new_user175	= { FOLLOW_WS_in_new_user175_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_new_user179  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_new_user179_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_new_user179	= { FOLLOW_TEXT_in_new_user179_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_new_character212  */
static	ANTLR3_BITWORD FOLLOW_14_in_new_character212_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_new_character212	= { FOLLOW_14_in_new_character212_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_character_name245  */
static	ANTLR3_BITWORD FOLLOW_13_in_character_name245_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_character_name245	= { FOLLOW_13_in_character_name245_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_character_name247  */
static	ANTLR3_BITWORD FOLLOW_WS_in_character_name247_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_character_name247	= { FOLLOW_WS_in_character_name247_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_character_name251  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_character_name251_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_character_name251	= { FOLLOW_TEXT_in_character_name251_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_pick_character284  */
static	ANTLR3_BITWORD FOLLOW_9_in_pick_character284_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_pick_character284	= { FOLLOW_9_in_pick_character284_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_pick_character286  */
static	ANTLR3_BITWORD FOLLOW_WS_in_pick_character286_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_pick_character286	= { FOLLOW_WS_in_pick_character286_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_pick_character290  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_pick_character290_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_pick_character290	= { FOLLOW_TEXT_in_pick_character290_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_login323  */
static	ANTLR3_BITWORD FOLLOW_10_in_login323_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_login323	= { FOLLOW_10_in_login323_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_login325  */
static	ANTLR3_BITWORD FOLLOW_WS_in_login325_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_login325	= { FOLLOW_WS_in_login325_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_login329  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_login329_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_login329	= { FOLLOW_TEXT_in_login329_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_login331  */
static	ANTLR3_BITWORD FOLLOW_WS_in_login331_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_login331	= { FOLLOW_WS_in_login331_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_login335  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_login335_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_login335	= { FOLLOW_TEXT_in_login335_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_look368  */
static	ANTLR3_BITWORD FOLLOW_11_in_look368_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000022) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_look368	= { FOLLOW_11_in_look368_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_look371  */
static	ANTLR3_BITWORD FOLLOW_WS_in_look371_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_look371	= { FOLLOW_WS_in_look371_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_6_in_look373  */
static	ANTLR3_BITWORD FOLLOW_6_in_look373_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_6_in_look373	= { FOLLOW_6_in_look373_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_look385  */
static	ANTLR3_BITWORD FOLLOW_11_in_look385_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_look385	= { FOLLOW_11_in_look385_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_look388  */
static	ANTLR3_BITWORD FOLLOW_WS_in_look388_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_look388	= { FOLLOW_WS_in_look388_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_7_in_look390  */
static	ANTLR3_BITWORD FOLLOW_7_in_look390_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_7_in_look390	= { FOLLOW_7_in_look390_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_look394  */
static	ANTLR3_BITWORD FOLLOW_WS_in_look394_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_look394	= { FOLLOW_WS_in_look394_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_look398  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_look398_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_look398	= { FOLLOW_TEXT_in_look398_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_12_in_move432  */
static	ANTLR3_BITWORD FOLLOW_12_in_move432_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_12_in_move432	= { FOLLOW_12_in_move432_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_WS_in_move434  */
static	ANTLR3_BITWORD FOLLOW_WS_in_move434_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_WS_in_move434	= { FOLLOW_WS_in_move434_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TEXT_in_move440  */
static	ANTLR3_BITWORD FOLLOW_TEXT_in_move440_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_TEXT_in_move440	= { FOLLOW_TEXT_in_move440_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start command
 * c_src/Mud.g:41:1: command[ErlNifEnv *env] returns [ERL_NIF_TERM value] : (cmd= new_user[env] |cmd= new_character[env] |cmd= character_name[env] |cmd= pick_character[env] |cmd= login[env] |cmd= look[env] |cmd= move[env] );
 */
static ERL_NIF_TERM
command(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    ERL_NIF_TERM cmd;
    #undef	RETURN_TYPE_cmd
    #define	RETURN_TYPE_cmd ERL_NIF_TERM

    /* Initialize rule variables
     */

    {
        {
            //  c_src/Mud.g:42:5: (cmd= new_user[env] |cmd= new_character[env] |cmd= character_name[env] |cmd= pick_character[env] |cmd= login[env] |cmd= look[env] |cmd= move[env] )

            ANTLR3_UINT32 alt1;

            alt1=7;

            switch ( LA(1) )
            {
            case 8:
            	{
            		alt1=1;
            	}
                break;
            case 14:
            	{
            		alt1=2;
            	}
                break;
            case 13:
            	{
            		alt1=3;
            	}
                break;
            case 9:
            	{
            		alt1=4;
            	}
                break;
            case 10:
            	{
            		alt1=5;
            	}
                break;
            case 11:
            	{
            		alt1=6;
            	}
                break;
            case TEXT:
            case 12:
            	{
            		alt1=7;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 1;
                EXCEPTION->state        = 0;


                goto rulecommandEx;

            }

            switch (alt1)
            {
        	case 1:
        	    // c_src/Mud.g:42:7: cmd= new_user[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_new_user_in_command51);
        	        cmd=new_user(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            cmd
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 2:
        	    // c_src/Mud.g:43:7: cmd= new_character[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_new_character_in_command65);
        	        cmd=new_character(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            cmd
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 3:
        	    // c_src/Mud.g:44:7: cmd= character_name[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_character_name_in_command79);
        	        cmd=character_name(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            cmd
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 4:
        	    // c_src/Mud.g:45:7: cmd= pick_character[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_pick_character_in_command92);
        	        cmd=pick_character(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            cmd
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 5:
        	    // c_src/Mud.g:46:7: cmd= login[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_login_in_command106);
        	        cmd=login(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            cmd
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 6:
        	    // c_src/Mud.g:47:7: cmd= look[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_look_in_command120);
        	        cmd=look(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            cmd
        	            ;
        	             
        	        }


        	    }
        	    break;
        	case 7:
        	    // c_src/Mud.g:48:7: cmd= move[env]
        	    {
        	        FOLLOWPUSH(FOLLOW_move_in_command133);
        	        cmd=move(ctx, env);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulecommandEx;
        	        }


        	        {
        	             value= 
        	            cmd
        	            ;
        	             
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulecommandEx; /* Prevent compiler warnings */
    rulecommandEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{

	            value= A("invalid_cmd");

	        
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end command */

/**
 * $ANTLR start new_user
 * c_src/Mud.g:54:1: new_user[ErlNifEnv *env] returns [ERL_NIF_TERM value] : 'create user' WS user= TEXT WS pass= TEXT ;
 */
static ERL_NIF_TERM
new_user(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    pANTLR3_COMMON_TOKEN    user;
    pANTLR3_COMMON_TOKEN    pass;

    /* Initialize rule variables
     */

    user       = NULL;
    pass       = NULL;

    {
        // c_src/Mud.g:55:5: ( 'create user' WS user= TEXT WS pass= TEXT )
        // c_src/Mud.g:55:7: 'create user' WS user= TEXT WS pass= TEXT
        {
             MATCHT(8, &FOLLOW_8_in_new_user167);
            if  (HASEXCEPTION())
            {
                goto rulenew_userEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_new_user169);
            if  (HASEXCEPTION())
            {
                goto rulenew_userEx;
            }


            user = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_new_user173);
            if  (HASEXCEPTION())
            {
                goto rulenew_userEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_new_user175);
            if  (HASEXCEPTION())
            {
                goto rulenew_userEx;
            }


            pass = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_new_user179);
            if  (HASEXCEPTION())
            {
                goto rulenew_userEx;
            }


            {

                            ERL_NIF_TERM userProp = PROP("username", BIN(user));
                            ERL_NIF_TERM passProp = PROP("password", BIN(pass));

                            ERL_NIF_TERM props = LIST(2, userProp, passProp);

                            
                value= make_cmd(env, "new_user", props);

                        
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulenew_userEx; /* Prevent compiler warnings */
    rulenew_userEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end new_user */

/**
 * $ANTLR start new_character
 * c_src/Mud.g:66:1: new_character[ErlNifEnv *env] returns [ERL_NIF_TERM value] : 'new character' ;
 */
static ERL_NIF_TERM
new_character(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    /* Initialize rule variables
     */

    {
        // c_src/Mud.g:67:5: ( 'new character' )
        // c_src/Mud.g:67:7: 'new character'
        {
             MATCHT(14, &FOLLOW_14_in_new_character212);
            if  (HASEXCEPTION())
            {
                goto rulenew_characterEx;
            }


            {

                            value= make_cmd(env, "new_character", LIST(0));

                        
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulenew_characterEx; /* Prevent compiler warnings */
    rulenew_characterEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end new_character */

/**
 * $ANTLR start character_name
 * c_src/Mud.g:73:1: character_name[ErlNifEnv *env] returns [ERL_NIF_TERM value] : 'my name is' WS character= TEXT ;
 */
static ERL_NIF_TERM
character_name(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    pANTLR3_COMMON_TOKEN    character;

    /* Initialize rule variables
     */

    character       = NULL;

    {
        // c_src/Mud.g:74:5: ( 'my name is' WS character= TEXT )
        // c_src/Mud.g:74:7: 'my name is' WS character= TEXT
        {
             MATCHT(13, &FOLLOW_13_in_character_name245);
            if  (HASEXCEPTION())
            {
                goto rulecharacter_nameEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_character_name247);
            if  (HASEXCEPTION())
            {
                goto rulecharacter_nameEx;
            }


            character = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_character_name251);
            if  (HASEXCEPTION())
            {
                goto rulecharacter_nameEx;
            }


            {

                            ERL_NIF_TERM charProp = PROP("name", BIN(character));

                            ERL_NIF_TERM props = LIST(1, charProp);

                            
                value= make_cmd(env, "character_name", props);

                        
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulecharacter_nameEx; /* Prevent compiler warnings */
    rulecharacter_nameEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end character_name */

/**
 * $ANTLR start pick_character
 * c_src/Mud.g:84:1: pick_character[ErlNifEnv *env] returns [ERL_NIF_TERM value] : 'join as' WS character= TEXT ;
 */
static ERL_NIF_TERM
pick_character(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    pANTLR3_COMMON_TOKEN    character;

    /* Initialize rule variables
     */

    character       = NULL;

    {
        // c_src/Mud.g:85:5: ( 'join as' WS character= TEXT )
        // c_src/Mud.g:85:7: 'join as' WS character= TEXT
        {
             MATCHT(9, &FOLLOW_9_in_pick_character284);
            if  (HASEXCEPTION())
            {
                goto rulepick_characterEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_pick_character286);
            if  (HASEXCEPTION())
            {
                goto rulepick_characterEx;
            }


            character = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_pick_character290);
            if  (HASEXCEPTION())
            {
                goto rulepick_characterEx;
            }


            {

                            ERL_NIF_TERM charProp = PROP("character", BIN(character));

                            ERL_NIF_TERM props = LIST(1, charProp);

                            
                value= make_cmd(env, "pick_character", props);

                        
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulepick_characterEx; /* Prevent compiler warnings */
    rulepick_characterEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end pick_character */

/**
 * $ANTLR start login
 * c_src/Mud.g:95:1: login[ErlNifEnv *env] returns [ERL_NIF_TERM value] : 'login' WS user= TEXT WS pass= TEXT ;
 */
static ERL_NIF_TERM
login(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    pANTLR3_COMMON_TOKEN    user;
    pANTLR3_COMMON_TOKEN    pass;

    /* Initialize rule variables
     */

    user       = NULL;
    pass       = NULL;

    {
        // c_src/Mud.g:96:5: ( 'login' WS user= TEXT WS pass= TEXT )
        // c_src/Mud.g:96:7: 'login' WS user= TEXT WS pass= TEXT
        {
             MATCHT(10, &FOLLOW_10_in_login323);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_login325);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


            user = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_login329);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


             MATCHT(WS, &FOLLOW_WS_in_login331);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


            pass = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_login335);
            if  (HASEXCEPTION())
            {
                goto ruleloginEx;
            }


            {

                            ERL_NIF_TERM userProp = PROP("username", BIN(user));
                            ERL_NIF_TERM passProp = PROP("password", BIN(pass));

                            ERL_NIF_TERM props = LIST(2, userProp, passProp);

                            
                value= make_cmd(env, "login", props);

                        
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleloginEx; /* Prevent compiler warnings */
    ruleloginEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end login */

/**
 * $ANTLR start look
 * c_src/Mud.g:107:1: look[ErlNifEnv *env] returns [ERL_NIF_TERM value] : ( 'look' ( WS 'around' )? | 'look' ( WS 'at' )? WS target= TEXT );
 */
static ERL_NIF_TERM
look(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    pANTLR3_COMMON_TOKEN    target;

    /* Initialize rule variables
     */

    target       = NULL;

    {
        {
            //  c_src/Mud.g:108:5: ( 'look' ( WS 'around' )? | 'look' ( WS 'at' )? WS target= TEXT )

            ANTLR3_UINT32 alt4;

            alt4=2;

            switch ( LA(1) )
            {
            case 11:
            	{
            		switch ( LA(2) )
            		{
            		case WS:
            			{
            				switch ( LA(3) )
            				{
            				case 6:
            					{
            						alt4=1;
            					}
            				    break;
            				case TEXT:
            				case 7:
            					{
            						alt4=2;
            					}
            				    break;

            				default:
            				    CONSTRUCTEX();
            				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            				    EXCEPTION->message      = (void *)"";
            				    EXCEPTION->decisionNum  = 4;
            				    EXCEPTION->state        = 2;


            				    goto rulelookEx;

            				}

            			}
            		    break;
            		case EOF:
            			{
            				alt4=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 4;
            		    EXCEPTION->state        = 1;


            		    goto rulelookEx;

            		}

            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 4;
                EXCEPTION->state        = 0;


                goto rulelookEx;

            }

            switch (alt4)
            {
        	case 1:
        	    // c_src/Mud.g:108:7: 'look' ( WS 'around' )?
        	    {
        	         MATCHT(11, &FOLLOW_11_in_look368);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	        // c_src/Mud.g:108:14: ( WS 'around' )?
        	        {
        	            int alt2=2;
        	            switch ( LA(1) )
        	            {
        	                case WS:
        	                	{
        	                		alt2=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt2)
        	            {
        	        	case 1:
        	        	    // c_src/Mud.g:108:15: WS 'around'
        	        	    {
        	        	         MATCHT(WS, &FOLLOW_WS_in_look371);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulelookEx;
        	        	        }


        	        	         MATCHT(6, &FOLLOW_6_in_look373);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulelookEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        {

        	                        value= make_cmd(env, "look", LIST(0));

        	                    
        	        }


        	    }
        	    break;
        	case 2:
        	    // c_src/Mud.g:111:7: 'look' ( WS 'at' )? WS target= TEXT
        	    {
        	         MATCHT(11, &FOLLOW_11_in_look385);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	        // c_src/Mud.g:111:14: ( WS 'at' )?
        	        {
        	            int alt3=2;
        	            switch ( LA(1) )
        	            {
        	                case WS:
        	                	{
        	                		switch ( LA(2) )
        	                		{
        	                		    case 7:
        	                		    	{
        	                		    		alt3=1;
        	                		    	}
        	                		        break;
        	                		}

        	                	}
        	                    break;
        	            }

        	            switch (alt3)
        	            {
        	        	case 1:
        	        	    // c_src/Mud.g:111:15: WS 'at'
        	        	    {
        	        	         MATCHT(WS, &FOLLOW_WS_in_look388);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulelookEx;
        	        	        }


        	        	         MATCHT(7, &FOLLOW_7_in_look390);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulelookEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	         MATCHT(WS, &FOLLOW_WS_in_look394);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	        target = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_look398);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelookEx;
        	        }


        	        {

        	                        ERL_NIF_TERM obj = PROP("target", BIN(target));
        	                        
        	            value= make_cmd(env, "look", LIST(1, obj));

        	                    
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulelookEx; /* Prevent compiler warnings */
    rulelookEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end look */

/**
 * $ANTLR start move
 * c_src/Mud.g:118:1: move[ErlNifEnv *env] returns [ERL_NIF_TERM value] : ( 'move' WS )? dir= TEXT ;
 */
static ERL_NIF_TERM
move(pMudParser ctx, ErlNifEnv *env)
{
    ERL_NIF_TERM value;


    pANTLR3_COMMON_TOKEN    dir;

    /* Initialize rule variables
     */

    dir       = NULL;

    {
        // c_src/Mud.g:119:5: ( ( 'move' WS )? dir= TEXT )
        // c_src/Mud.g:119:7: ( 'move' WS )? dir= TEXT
        {
            // c_src/Mud.g:119:7: ( 'move' WS )?
            {
                int alt5=2;
                switch ( LA(1) )
                {
                    case 12:
                    	{
                    		alt5=1;
                    	}
                        break;
                }

                switch (alt5)
                {
            	case 1:
            	    // c_src/Mud.g:119:8: 'move' WS
            	    {
            	         MATCHT(12, &FOLLOW_12_in_move432);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemoveEx;
            	        }


            	         MATCHT(WS, &FOLLOW_WS_in_move434);
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemoveEx;
            	        }


            	    }
            	    break;

                }
            }

            dir = (pANTLR3_COMMON_TOKEN) MATCHT(TEXT, &FOLLOW_TEXT_in_move440);
            if  (HASEXCEPTION())
            {
                goto rulemoveEx;
            }


            {

                            ERL_NIF_TERM direction = PROP("exit", BIN(dir));
                            
                value= make_cmd(env, "move", LIST(1, direction));

                        
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemoveEx; /* Prevent compiler warnings */
    rulemoveEx: ;

    if	(HASEXCEPTION())
    {
	/* catch(decl,action)
	 */
	{
	}


    }
    else
    {
    }
    return value;
}
/* $ANTLR end move */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
